#!/bin/sh

if [ $(hostname) == "desktop" ]; then
  xrandr --dpi 96x96 &
  ckb-next --background &
fi

if [ $(hostname) == "laptop" ]; then
  nm-applet &
fi

xbindkeys &
xxkb &
~/.fehbg &
steam-native -silent &
