#!/bin/sh

if [ $(hostname) == "node01" ]; then
  xrandr --dpi 96x96 &
  ckb-next --background &
fi

if [ $(hostname) == "node02" ]; then
  nm-applet &
fi

xbindkeys &
xxkb &
~/.fehbg &
#steam-native -silent &
