#!/bin/sh

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

export STEAM_FRAME_FORCE_CLOSE=1

if [ $(hostname) == "adjunct01" ]; then
  ckb-next -b&
  nvidia-settings -a "[gpu:0]/GPUFanControlState=1" -a "[fan:0]/GPUTargetFanSpeed=100"&
fi

#if [ $(hostname) == "node02" ]; then
#fi

nm-applet &
xbindkeys &
fcitx &
~/.fehbg &
picom &
#steam-native -silent &
